### PR TITLE
Use `Report` effect instead of `error`

### LINKED ISSUE #17: Add support for negation operation
## Description

Add support for the unary minus operator (i.e., `-exp`).

## Motivation

In `haskell-src-exts` there is an [AST node](https://hackage.haskell.org/package/haskell-src-exts-1.23.0/docs/Language-Haskell-Exts-Syntax.html#v:NegApp) for the application of the unary minus operator. This operator is currently not supported. For example, transforming the following function.

```haskell
abs :: Integer -> Integer
abs n | n < 0     = -n
      | otherwise = n
```

Causes the following error.

```
haskell-src-transformations: Rename: Exp caused an error
CallStack (from HasCallStack):
  error, called at src/lib/Renaming.hs:96:29 in haskell-src-transformations-0.1.1.0-inplace:Renaming
```

Since the unary minus operator is supported by the Free Compiler, it should also be supported by this library such that users can still enable pattern matching compilation even if their program requires negation.

## Alternatives

The `negate` function from the `Prelude` can be used as a workaround until support for the unary minus operator is added.

### LINKED ISSUE #38: Use `Report` effect instead of `error`
## Description

Replace all `error` calls by `reportFatal`.

## Motivation

In #28 effects for error reporting have been added and in #37 the `PM` monad was replaced by Polysemy effects. While the state effects are used in the algorithm already, the `Report` effect is still used in `Main` only. In the next step, errors in other modules should be handled explicitly as well.

### LINKED ISSUE #41: Non-variable pattern bindings are discarded
### Description

If a module contains non-variable pattern bindings, they are discarded during the conversion from the intermediate representation to `haskell-src-exts`.

### Steps to Reproduce

Consider the following module.

```haskell
module Test where

foo = 42
(bar, baz) = (1, 2)
qux = 1337
```

#### Expected Behavior

When the pattern matching compiler is applied to the module above, the output module should be identical because `foo` and `qux` don't have to be transformed and `(bar, baz)` is skipped since it is not supported.

#### Actual Behavior

During the transformation `FromHSE`, the pattern binding `(bar, baz)` is discarded. `ToHSE` tries to interleave unsupported declarations with the transformed AST nodes. However, `ToHSE` currently [does not check](https://github.com/FreeProving/haskell-src-transformations/blob/937371112b156f22b5a8851d9906e3be68e79cbf/src/lib/HST/Frontend/ToHSE.hs#L35) whether a `PatBind` is a variable binding or not supported. `PatBind`ings in the input module are always replaced by the next transformed declaration. Thus, the binding of `(bar, baz)` is replaced by `qux = 1337`. The remaining declaration of `qux` in the input module is also copied to the output.

```haskell
module Test where

foo = 42
qux = 1337
qux = 1337
```

### Versions

 - Git commit: 1e89a4584da5cfa882706a671ae850537b91402f
 - `ghc --version`: 8.6.5
 - `cabal --version`: 2.4.1.0
 - OS: Ubuntu 20.04 LTS

### Tasks

Since it is error prone to reconstruct the original module in `ToHSE` and unsupported declarations in `let` expressions are discarded as well, we want to add additional information about the original module to the AST.

 - [x] Add a constructor `S.UnsupportedDecl` to `S.Decl`.
 - [x] Remove the `S.TypeSig` constructor from `S.Decl`.
 - [x] Add additional information to `S.Module` and `S.DataDecl` for reconstruction of original module or declaration.
   + [x] Add new type family for declaration data type and module header.

### PR DESCRIPTION
**Pull request by just95**
### Issue

Closes #38.
Closes #17 by completing pattern matching for `S.NegApp`.
Closes #41 in order to complete pattern matching in `HST.Frontend.ToHSE`.

### Additional Notes

 - Support for `newtype` declarations was added in order to complete pattern matching in `HST.Frontend.FromHSE`. `newtype` declarations can be represented by the existing `DataDecl` nodes.

### CODE REVIEW

File: src/lib/HST/CoreAlgorithm.hs [hunk 1]
```diff
@@ -360,35 +379,36 @@ translateApp _              = error "translateApp: Unsupported pattern"
...
-  nvars <- newVars (length ps)
+    decomposeConPat (S.PInfixApp S.NoSrcSpan n listCon (S.PList S.NoSrcSpan nv))
+decomposeConPat (S.PTuple _ bxd ps) = do
+  nvars <- replicateM (length ps) (freshVarPat genericFreshPrefix)
   return (S.PTuple S.NoSrcSpan bxd nvars, nvars, ps)
 -- wildcards no longer needed as cons
-getConst (S.PWildCard _) = return (S.PWildCard S.NoSrcSpan, [], [])
-getConst _               = error "wrong Pattern in getConst"
+decomposeConPat (S.PWildCard _) = return (S.PWildCard S.NoSrcSpan, [], [])
+decomposeConPat _               = error "wrong Pattern in decomposeConPat"
```
Comment (stu204146-kiel) [inline src/lib/HST/CoreAlgorithm.hs]: There are still errors in here

File: src/lib/HST/CoreAlgorithm.hs [hunk 2]
```diff
@@ -183,37 +200,30 @@ computeAlts x xs eqs er = do
 
 -- | Looks up the constructors of the data type that is matched by the given
 --   @case@ expression alternatives for which there are no alternatives already.
-getMissingConstrs :: [S.Alt a] -> PM a [Constructor a]
-getMissingConstrs []   = error "getMissingConstrs: empty list"
+getMissingConstrs :: Member (Env a) r => [S.Alt a] -> Sem r [ConEntry a]
+getMissingConstrs []   = error "getMissingConstrs: empty case"
```
Comment (stu204146-kiel) [inline src/lib/HST/CoreAlgorithm.hs]: Here is also an error that should be replaced by report

**Review by stu204146-kiel — CHANGES_REQUESTED** [review]

File: src/lib/HST/Application.hs [hunk 3]
```diff
@@ -103,25 +109,38 @@ hasCons (S.InfixMatch _ p1 _ ps _ _) = any isCons (p1 : ps)
...
+    return (pats, expr)
+  matchToEquation (S.InfixMatch _ pat _ pats rhs _) = do
+    expr <- fromUnguardedRhs rhs
+    return (pat : pats, expr)
+
+  -- | Gets the expressions of the given right-hand side of a rule.
+  fromUnguardedRhs :: Member Report r => S.Rhs a -> Sem r (S.Exp a)
+  fromUnguardedRhs (S.UnGuardedRhs _ expr) = return expr
+  fromUnguardedRhs (S.GuardedRhss _ _) =
+    reportFatal $ Message Internal "Expected unguarded right hand side."
```
Comment (stu204767) [inline src/lib/HST/Application.hs]:
```suggestion
    reportFatal $ Message Internal "Expected unguarded right-hand side."
```

File: src/lib/HST/Application.hs [hunk 4]
```diff
@@ -103,25 +109,38 @@ hasCons (S.InfixMatch _ p1 _ ps _ _) = any isCons (p1 : ps)
...
+  --   There must be no guards on the right-hand side.
+  matchToEquation :: Member Report r => S.Match a -> Sem r (Eqs a)
+  matchToEquation (S.Match _ _ pats rhs _) = do
+    expr <- fromUnguardedRhs rhs
+    return (pats, expr)
+  matchToEquation (S.InfixMatch _ pat _ pats rhs _) = do
+    expr <- fromUnguardedRhs rhs
+    return (pat : pats, expr)
+
+  -- | Gets the expressions of the given right-hand side of a rule.
```
Comment (stu204767) [inline src/lib/HST/Application.hs]:
```suggestion
  -- | Gets the expression of the given unguarded right-hand side of a rule.
```

File: src/lib/HST/Environment/Renaming.hs [hunk 5]
```diff
@@ -119,20 +117,24 @@ instance Rename (S.Alt s) where
...
-    S.PParen l p        -> S.PParen l $ rename s p
+    S.PParen l p        -> S.PParen l (rename s p)
     S.PWildCard l       -> S.PWildCard l
 
 -- | 'Rename' instance for right-hand sides.
 --
---   Applies the substitution to the expression on the right-hand side.
---   There must be no guards.
+--   Applies the substitution to guards and the expression on the right-hand
+--   sides.
```
Comment (stu204767) [inline src/lib/HST/Environment/Renaming.hs]:
```suggestion
--   Applies the substitution to all guard and body expressions of the
--   right-hand side(s).
```

File: src/test/HST/ApplicationTests.hs [hunk 6]
```diff
@@ -141,10 +139,10 @@ testProcessModule = context "processModule" $ do
     expected <- parseTestModule $ unlines
       [ "module A where"
       , "id :: a -> a"
-      , "id a0 = let a2 = undefined"
-      , "            a1 = case a0 of"
+      , "id a0 = let a1 = case a0 of"
       , "              a3 -> if otherwise then a3"
       , "                                 else a2"
+      , "            a2 = undefined"
       , "         in a1"
```
Comment (stu204767) [inline src/test/HST/ApplicationTests.hs]:
```suggestion
      , "        in a1"
```

File: src/lib/HST/Feature/GuardElimination.hs [hunk 7]
```diff
@@ -1,255 +1,269 @@
...
+--
+--   There is one @let@ binding for each rule or alternative and an additional
+--   binding for the error expression. The @i@-th binding uses the @(i + 1)@-th
+--   binding as an error expression.
+generateLet
+  :: Member Fresh r
+  => [S.Exp a] -- ^ Variables to match.
+  -> S.Exp a   -- ^ Expression to use if patterns don't match or the guard is
+               --   not satisfied.
+  -> [GExp a]  -- ^ Patters to match and the corrsponding right-hand sides.
```
Comment (stu204767) [inline src/lib/HST/Feature/GuardElimination.hs]:
```suggestion
  -> [GExp a]  -- ^ Patterns to match and the corresponding right-hand sides.
```

File: src/lib/HST/Feature/GuardElimination.hs [hunk 8]
```diff
@@ -1,255 +1,269 @@
...
+  let startVarExpr : nextVarExprs = map S.var varNames
+      ifExprs = zipWith (rhsToIf . gExpRhs) gExps nextVarExprs
+  ifExprs' <- mapM applyGEExp ifExprs
+  let exprPats  = map (zip vs . gExpPats) gExps
+      caseExprs = zipWith3 generateNestedCases ifExprs' nextVarExprs exprPats
+      decls     = zipWith makeVarBinding varNames (caseExprs ++ [err])
+  return $ S.Let S.NoSrcSpan (S.BDecls S.NoSrcSpan decls) startVarExpr
+
+-- | Creates a function declaration for a @let@ binding of a variable with the
+--   given name to the given expression.
```
Comment (stu204767) [inline src/lib/HST/Feature/GuardElimination.hs]: That comment is confusing to read. This should be better:
```suggestion
-- | Creates a function declaration for a @let@ binding that binds a variable
--   with the given name to the given expression.
```

File: src/lib/HST/Feature/GuardElimination.hs [hunk 9]
```diff
@@ -1,255 +1,269 @@
...
-  -> S.Exp a              -- the other pattern (in case pattern match or guard fails)
-  -> [(S.Pat a, S.Pat a)] -- Patterns to match (PVar , Pattern)
+-------------------------------------------------------------------------------
+-- @case@ Expressions                                                        --
+-------------------------------------------------------------------------------
+
+-- | Generates nested case expression for each variable and pattern pair.
+--
+--   @'generateNestedCases' e f [(x₁, p₁), …, (xₙ, pₙ)]@ produces an expression
+--   of the following form.
```
Comment (stu204767) [inline src/lib/HST/Feature/GuardElimination.hs:76]:
```suggestion
--   of the following form:
```

File: src/lib/HST/Feature/GuardElimination.hs [hunk 10]
```diff
@@ -1,255 +1,269 @@
...
--- Generates a recursive case expression for each variable and pattern pair
-createCase
-  :: S.Exp a              -- ifThenElse
-  -> S.Exp a              -- the other pattern (in case pattern match or guard fails)
-  -> [(S.Pat a, S.Pat a)] -- Patterns to match (PVar , Pattern)
+-------------------------------------------------------------------------------
+-- @case@ Expressions                                                        --
+-------------------------------------------------------------------------------
+
+-- | Generates nested case expression for each variable and pattern pair.
```
Comment (stu204767) [inline src/lib/HST/Feature/GuardElimination.hs]:
```suggestion
-- | Generates a nested case expression for each variable and pattern pair.
```

File: src/lib/HST/Feature/GuardElimination.hs [hunk 11]
```diff
@@ -1,255 +1,269 @@
...
+--
+--   @'generateNestedCases' e f [(x₁, p₁), …, (xₙ, pₙ)]@ produces an expression
+--   of the following form.
+--
+--   > case x₁ of { p₁ -> (… case xₙ of { pₙ -> e ; _ -> f }  …) ; _ -> f }
+generateNestedCases
+  :: S.Exp a              -- ^ Expression to use if all pattern match.
```
Comment (stu204767) [inline src/lib/HST/Feature/GuardElimination.hs]:
```suggestion
  :: S.Exp a              -- ^ Expression to use if all patterns match.
```

File: src/lib/HST/Feature/GuardElimination.hs [hunk 12]
```diff
@@ -1,255 +1,269 @@
...
---       Case () (translatePVar v)
---               [S.alt p res, S.alt B.wildcard next]) i vps
-createCase i _    []             = i
-createCase i next ((v, p) : vps) = S.Case
-  S.NoSrcSpan
-  (CA.translatePVar v)
-  [S.alt p (createCase i next vps), S.alt (S.PWildCard S.NoSrcSpan) next]
+generateNestedCases successExpr failExpr = foldr generateNestedCase successExpr
+ where
+  {- generateNestedCase :: (S.Exp a, S.Pat a) -> S.Exp a -> S.Exp a -}
```
Comment (stu204767) [inline src/lib/HST/Feature/GuardElimination.hs:86]: Why is the type signature commented out?

File: src/lib/HST/Feature/GuardElimination.hs [hunk 13]
```diff
@@ -1,255 +1,269 @@
...
+--   expression and the expression on the right-hand side is used as
+--   the @then@ branch. The second argument is the @else@ branch.
+guardedRhsToIf :: S.GuardedRhs a -> S.Exp a -> S.Exp a
+guardedRhsToIf (S.GuardedRhs _ e1 e2) = S.If S.NoSrcSpan e1 e2
+
+-------------------------------------------------------------------------------
+-- Guard Elimination                                                         --
+-------------------------------------------------------------------------------
+
+-- | Applies guard elimination on @case@ expression in the given expression.
```
Comment (stu204767) [inline src/lib/HST/Feature/GuardElimination.hs]:
```suggestion
-- | Applies guard elimination on @case@ expressions in the given expression.
```

**Review by stu204767 — CHANGES_REQUESTED** [review]

File: src/lib/HST/Feature/GuardElimination.hs (hunk 9 above)
Comment (just95) [reply src/lib/HST/Feature/GuardElimination.hs:76]: If we used a colon here, the sentence would never end with a period.

File: src/lib/HST/Feature/GuardElimination.hs (hunk 12 above)
Comment (just95) [reply src/lib/HST/Feature/GuardElimination.hs:86]: Since `failExpr` is used in `generateNestedCase` the `a` in the type signature of `generateNestedCase` must be the same `a` as in the type signature of `generateNestedCases`. Due to Haskells type variable scoping rules, it is not possible to specify the type of `geneateNestedCase` without language extensions. Thus, the type signature must be commented out as suggested by our [Haskell Styleguide](https://github.com/FreeProving/guidelines/blob/main/CONTRIBUTING.md#add-type-signatures-for-all-function-declarations).

File: src/lib/HST/Feature/GuardElimination.hs (hunk 9 above)
Comment (stu204767) [reply src/lib/HST/Feature/GuardElimination.hs:76]: I don't think this is a problem. I've found [this article](https://www.grammarbook.com/punctuation/colons.asp) and looking at the first example of rule 3, it seems to be correct as well.

Comment (just95) [reply src/lib/HST/Feature/GuardElimination.hs:76]: The article also states that "there are no hard and fast rules, except be consistent". The rule that I've adopted from @ichistmeinname (and which we should stick to for consistency's sake) is that a colon is only used if the sentence still ends with a period eventually.

Comment (stu204767) [reply src/lib/HST/Feature/GuardElimination.hs:76]: Okay, but I don't think this is a sensible rule if it prevents the usage of colons in cases like this. The only option to add a colon here would be to add a period after the example, which would look weird.
The choice between a colon and a period is a stylistic one in the end. I would definitely choose the colon in this case (and I'm [not the only one](https://english.stackexchange.com/questions/96286/period-or-colon)), but I'm fine with a period as well.

File: src/lib/HST/Effect/PatternStack.hs [hunk 14]
```diff
@@ -0,0 +1,74 @@
...
+import qualified HST.Frontend.Syntax           as S
+
+-------------------------------------------------------------------------------
+-- Effect and Actions                                                        --
+-------------------------------------------------------------------------------
+
+-- | An effect capable of pushing and poping patterns variables have been
+--   matched against to a stack.
+data PatternStack a m b where
+  PushPattern ::S.QName a -> S.Pat a -> PatternStack a m ()
```
Comment (stu204146-kiel) [inline src/lib/HST/Effect/PatternStack.hs:41]: It should be a whitespace between the two colons and the type expression
```suggestion
  PushPattern :: S.QName a -> S.Pat a -> PatternStack a m ()
```

File: src/lib/HST/Effect/PatternStack.hs [hunk 15]
```diff
@@ -0,0 +1,74 @@
...
+
+-- | Interprets the given computation by providing one stack for each variable.
+runPatternStack :: Sem (PatternStack a ': r) b -> Sem r b
+runPatternStack = evalState Map.empty . patternStackToState
+ where
+  patternStackToState
+    :: Sem (PatternStack a ': r) b -> Sem (State (StackMap a) ': r) b
+  patternStackToState = reinterpret \case
+    PushPattern name pat -> modify $ Map.alter (maybeCons pat) name
+    PeekPattern name     -> gets $ fmap head . Map.lookup name
```
Comment (stu204146-kiel) [inline src/lib/HST/Effect/PatternStack.hs:62]: Here, the computation can fail if the list is empty. I would catch the error by returning a `Maybe`.

File: src/lib/HST/Environment/Renaming.hs [hunk 16]
```diff
@@ -37,24 +37,23 @@ class TermSubst c where
...
-    _                  -> error "TermSubst: Exp caused an error"
+  substitute s (S.Var l qname  ) = s (S.Var l qname)
+  substitute _ (S.Con l qname  ) = S.Con l qname
+  substitute _ (S.Lit l literal) = S.Lit l literal
+  substitute s (S.InfixApp l e1 qop e2) =
+    S.InfixApp l (substitute s e1) qop (substitute s e2)
+  substitute s (S.NegApp l e    ) = S.NegApp l (substitute s e)
+  substitute s (S.App    l e1 e2) = S.App l (substitute s e1) (substitute s e2)
+  substitute s (S.Lambda l ps e ) = S.Lambda l ps (substitute s e)
+  substitute s (S.Let    l b  e ) = S.Let l b $ substitute s e
```
Comment (stu204146-kiel) [inline src/lib/HST/Environment/Renaming.hs:48]: It is not ensured that name clashes are resolved: Example `let x = 1 in e + x`. If we substitute `e` by `x` we get a name clash

File: src/lib/HST/Effect/PatternStack.hs (hunk 14 above)
Comment (just95) [reply src/lib/HST/Effect/PatternStack.hs:41]: I agree, but Brittany would change it back. We will have to wait for <https://github.com/FreeProving/guidelines/issues/5>.

File: src/lib/HST/Effect/PatternStack.hs (hunk 15 above)
Comment (just95) [reply src/lib/HST/Effect/PatternStack.hs:62]: The computation cannot fail since entries are added and removed with `PushPattern` and `PopPattern` only. `PopPattern` removes the entry from the map if the list is empty via `maybeTail`. Thus, `Map.lookup` (and consequently `PeekPattern`) returns `Nothing` if there is no pattern for `name`. If `Map.lookup` returns a `Just`, the list of patterns is guaranteed to be non-empty.

File: src/lib/HST/Environment/Renaming.hs (hunk 16 above)
Comment (just95) [reply src/lib/HST/Environment/Renaming.hs:48]: That's true and a general problem of the `Renaming` module. The issue has been reported as #16 already.

File: src/lib/HST/Effect/PatternStack.hs [hunk 17]
```diff
@@ -0,0 +1,74 @@
+{-# LANGUAGE TemplateHaskell, ScopedTypeVariables #-}
+{-# LANGUAGE LambdaCase, BlockArguments #-}
+
+-- | This module defines an effect for computations that can save patterns
+--   variables have been matched against on a stack.
```
Comment (stu204767) [inline src/lib/HST/Effect/PatternStack.hs]: I'm not sure if this is what you meant:
```suggestion
-- | This module defines an effect for computations that can save pattern
--   variables that have been matched against on a stack.
```

File: src/lib/HST/Effect/PatternStack.hs [hunk 18]
```diff
@@ -0,0 +1,74 @@
...
+
+
+import qualified HST.Frontend.Syntax           as S
+
+-------------------------------------------------------------------------------
+-- Effect and Actions                                                        --
+-------------------------------------------------------------------------------
+
+-- | An effect capable of pushing and poping patterns variables have been
+--   matched against to a stack.
```
Comment (stu204767) [inline src/lib/HST/Effect/PatternStack.hs]: See the comment above.
```suggestion
-- | An effect capable of pushing and popping patterns that variables have been
--   matched against to a stack.
```

File: src/lib/HST/Environment/LookupOrReport.hs [hunk 19]
```diff
@@ -0,0 +1,61 @@
+-- | This module contains variations of the "HST.Environment" lookup functions
+--   that don't return @Maybe@ values but report fatal error if a data or type
+--   constructor cannot be found in the environment.
```
Comment (stu204767) [inline src/lib/HST/Environment/LookupOrReport.hs]:
```suggestion
--   that don't return @Maybe@ values but report a fatal error if a data or
--   type constructor cannot be found in the environment.
```

File: src/lib/HST/Feature/Optimization.hs [hunk 20]
```diff
@@ -6,63 +6,84 @@ module HST.Feature.Optimization
...
-    return $ S.List S.NoSrcSpan es'
-  S.Paren _ e -> do
-    e' <- optimize e
-    return $ S.Paren S.NoSrcSpan e'
-  c -> return c
+optimize :: Members '[Fresh, Report] r => S.Exp a -> Sem r (S.Exp a)
+optimize = runPatternStack . optimize'
+
+-- | Like 'optimize' but can access a stack of patterns for each local
+--   variable to remember which patterns variables have been matched
```
Comment (stu204767) [inline src/lib/HST/Feature/Optimization.hs]:
```suggestion
--   variable to remember the patterns that variables have been matched
```

File: src/lib/HST/Frontend/FromHSE.hs [hunk 21]
```diff
@@ -25,201 +44,437 @@ data HSE
...
+-- Only variable pattern bindings are supported. The user is informed if there
+-- are unsupported variable patterns that are skipped.
+transformDecl (HSE.PatBind s (HSE.PVar _ name) rhs mBinds) = do
+  match' <- transformMatch (HSE.Match s name [] rhs mBinds)
+  return $ S.FunBind (transformSrcSpan s) [match']
+transformDecl decl@(HSE.PatBind s _ _ _) = do
+  skipNotSupported "Non-variable pattern bindings"
+  return $ S.OtherDecl (transformSrcSpan s) decl
+
+-- Type classes and type class instances ar enot supported. The user is
```
Comment (stu204767) [inline src/lib/HST/Frontend/FromHSE.hs]:
```suggestion
-- Type classes and type class instances are not supported. The user is
```

File: src/lib/HST/Frontend/FromHSE.hs [hunk 22]
```diff
@@ -25,201 +44,437 @@ data HSE
...
+-- explicitly informed that the declaration is skipped since they might
+-- contain pattern matching.
+transformDecl decl@(HSE.ClassDecl s _ _ _ _) = do
+  skipNotSupported "Type classes"
+  return $ S.OtherDecl (transformSrcSpan s) decl
+transformDecl decl@(HSE.InstDecl s _ _ _) = do
+  skipNotSupported "Type class instances"
+  return $ S.OtherDecl (transformSrcSpan s) decl
+
+-- GADTs and pattern synonyms are not supported. The user us explicitly
```
Comment (stu204767) [inline src/lib/HST/Frontend/FromHSE.hs]:
```suggestion
-- GADTs and pattern synonyms are not supported. The user is explicitly
```

File: src/lib/HST/Frontend/Syntax.hs [hunk 23]
```diff
@@ -36,53 +42,90 @@ type family TypeExp a
...
 
 -- | A representation of a Haskell module.
 --
---   Only contains a module name and a list of declarations. When transforming
---   such a module back to a complete representation of a Haskell module, it
---   has to be enriched by other information (for example the module header and
---   unsupported declarations) from the original module.
-data Module a = Module (Maybe (ModuleName a)) [Decl a]
+--   The pattern matching compiler only needs to know the declarations of
+--   the module. All other information is stored in the 'OriginalModuleHead'.
```
Comment (stu204767) [inline src/lib/HST/Frontend/Syntax.hs]:
```suggestion
--   The pattern matching compiler only needs to know the declarations and the
--   name of the module. All other information is stored in the
--   'OriginalModuleHead'.
```

File: src/lib/HST/Frontend/Syntax.hs [hunk 24]
```diff
@@ -36,53 +42,90 @@ type family TypeExp a
...
+  getSrcSpan (DataDecl srcSpan _ _ _) = srcSpan
+  getSrcSpan (FunBind   srcSpan _   ) = srcSpan
+  getSrcSpan (OtherDecl srcSpan _   ) = srcSpan
+
 -------------------------------------------------------------------------------
 -- Data Type Declarations                                                    --
 -------------------------------------------------------------------------------
 
 -- | A data constructor. Does not include a source span and should not be
 --   transformed back.
```
Comment (stu204767) [inline src/lib/HST/Frontend/Syntax.hs]: The comment needs to be adjusted as well:
```suggestion
-- | A data constructor. Should not be transformed back.
```

File: src/lib/HST/Frontend/Syntax.hs [hunk 25]
```diff
@@ -170,34 +258,116 @@ data Pat a = PVar (SrcSpan a) (Name a)
...
+instance HasSrcSpan Pat where
+  getSrcSpan (PVar srcSpan _         ) = srcSpan
+  getSrcSpan (PInfixApp srcSpan _ _ _) = srcSpan
+  getSrcSpan (PApp   srcSpan _ _     ) = srcSpan
+  getSrcSpan (PTuple srcSpan _ _     ) = srcSpan
+  getSrcSpan (PParen srcSpan _       ) = srcSpan
+  getSrcSpan (PList  srcSpan _       ) = srcSpan
+  getSrcSpan (PWildCard srcSpan      ) = srcSpan
+
+-- | Converts a pattern to an expressions.
```
Comment (stu204767) [inline src/lib/HST/Frontend/Syntax.hs]:
```suggestion
-- | Converts a pattern to an expression.
```

File: src/lib/HST/Frontend/Syntax.hs [hunk 26]
```diff
@@ -170,34 +258,116 @@ data Pat a = PVar (SrcSpan a) (Name a)
...
+--
+--   The additional source span information is taken from the given name.
+unQual :: Name a -> QName a
+unQual name = UnQual (getSrcSpan name) name
+
+-- | Wraps a name with 'Special'.
+--
+--   The additional source span information is taken from the given name.
+special :: SpecialCon a -> QName a
+special specialCon = Special (getSrcSpan specialCon) specialCon
```
Comment (stu204767) [inline src/lib/HST/Frontend/Syntax.hs:321]: Why are these individual function when they could be part of the `QNameLike` instances for `Name`s and `SpecialCon`s?

File: src/lib/HST/Frontend/ToHSE.hs [hunk 27]
```diff
@@ -13,38 +13,46 @@ module HST.Frontend.ToHSE where
...
-    aDecl : combineDecls oDecls' aDecls'
-  combineDecls (HSE.PatBind _ _ _ _ : oDecls') (aDecl : aDecls') =
-    aDecl : combineDecls oDecls' aDecls'
-  combineDecls (oDecl : oDecls') aDecls' = oDecl : combineDecls oDecls' aDecls'
-  combineDecls []                aDecls' = aDecls'
-transformModule _ _ = error "Unsupported Module type"
+--   module into the @haskell-src-exts@ representation of a Haskell module.
+--
+--   The module head is restored from the original module head. The module
+--   name field does not affect the name of the resulting module..
```
Comment (stu204767) [inline src/lib/HST/Frontend/ToHSE.hs]:
```suggestion
--   name field does not affect the name of the resulting module.
```

File: src/lib/HST/Util/PrettyName.hs [hunk 28]
```diff
@@ -0,0 +1,57 @@
...
+
+-- | Pretty prints a name.
+instance PrettyName (S.Name a) where
+  prettyName = prettyNameWithPrefix ""
+
+-- | Helper functions for 'PrettyName' instance of 'S.Name' and 'S.QName'
+--   that pretty prints a name but adds a prefix.
+--
+--    The prefix is added before the identifier or symbol. In case of symbolic
+--    names, the prefix is within the parentheses.
```
Comment (stu204767) [inline src/lib/HST/Util/PrettyName.hs]:
```suggestion
--   The prefix is added before the identifier or symbol. In case of symbolic
--   names, the prefix is within the parentheses.
```

**Review by stu204767 — CHANGES_REQUESTED** [review]

File: src/lib/HST/Frontend/Syntax.hs (hunk 26 above)
Comment (just95) [reply src/lib/HST/Frontend/Syntax.hs:321]: I just thought that

```haskell
patToExp (PVar srcSpan name) = Var srcSpan (unQual name)
```

would be more readable than

```haskell
patToExp (PVar srcSpan name) = Var srcSpan (toQName name)
```

File: src/lib/HST/Frontend/Syntax.hs (hunk 24 above)
Comment (just95) [reply src/lib/HST/Frontend/Syntax.hs]:
```suggestion
-- | A data constructor.
--
--   Data constructors should not be converted back. The original
--   constructor declaration should be part of the 'OriginalDecl'
--   of a 'DataDecl'.
```

File: src/lib/HST/Effect/PatternStack.hs (hunk 17 above)
Comment (just95) [reply src/lib/HST/Effect/PatternStack.hs]: I agree that it is difficult to parse that sentence. What I mean is that the computation can store patterns that variables have been matched against. For example in

```haskell
case xs of
  (x : xs') -> …
```

the pattern `(x : xs')` would be pushed on the stack for the variable `xs`.

Comment (stu204767) [reply src/lib/HST/Effect/PatternStack.hs]: Ha, this is an advantage of compound words: You know that separate nouns are separate subjects/objects in a sentence, while you can only guess from the context without them. In this case, I would suggest:
```suggestion
-- | This module defines an effect for computations which can save patterns
--   that variables have been matched against on a stack.
```
I have also updated my other suggestions regarding this sentence structure.

File: src/lib/HST/Frontend/Syntax.hs (hunk 26 above)
Comment (stu204767) [reply src/lib/HST/Frontend/Syntax.hs:321]: Hm, there is no difference in readability to me. What do you think, @stu204146-kiel?

File: src/lib/HST/Frontend/Syntax.hs [hunk 29]
```diff
@@ -114,8 +115,11 @@ instance HasSrcSpan Decl where
 -- Data Type Declarations                                                    --
 -------------------------------------------------------------------------------
 
--- | A data constructor. Does not include a source span and should not be
---   transformed back.
+-- | A data constructor.
+--
+--   Data constructors should not be converted back. The original
+--   constructor declaration should be part of the 'OriginalDecl'
+--   of a 'DataDecl'.
```
Comment (stu204767) [inline src/lib/HST/Frontend/Syntax.hs]: Did you use another limit than 80 characters inadvertently or deliberately?
```suggestion
--   Data constructors should not be converted back. The original constructor
--   declaration should be part of the 'OriginalDecl' of a 'DataDecl'.
```

File: src/lib/HST/Frontend/FromHSE.hs [hunk 30]
```diff
@@ -25,201 +44,437 @@ data HSE
...
+  reportFatal $ Message Error $ feature ++ " are not supported!"
+
+-- | Informs the user that the given feature is not supported and the
+--   corresponding AST node will be skipped.
+skipNotSupported
+  :: Member Report r
+  => String -- ^ The name of the feature (plural) that is not supported.
+  -> Sem r ()
+skipNotSupported feature =
+  report $ Message Info $ feature ++ " are not supported and will be skipped!"
```
Comment (stu204767) [inline src/lib/HST/Frontend/FromHSE.hs:72]: These functions will be identical for the GHC transformation. I will copy them for now into `FromGHC.hs`, so I can start working with using `report` instead of `error` in the GHC modules, but they should be moved to another module, maybe `HST.Effect.Report`.

Comment (just95) [reply src/lib/HST/Frontend/FromHSE.hs:72]: See also #40.

File: src/lib/HST/Frontend/FromHSE.hs [hunk 31]
```diff
@@ -25,201 +44,437 @@ data HSE
...
 
 -- | Transforms an HSE binding group into an HST binding group.
-transformBinds :: HSE.Binds HSE.SrcSpanInfo -> S.Binds HSE
-transformBinds (HSE.BDecls s decls) = S.BDecls
-  (transformSrcSpan s)
-  (map (fromMaybe (error "Unsupported declaration") . transformDecl) decls)
-transformBinds _ = error "Implicit bindings are not supported"
+transformBinds
+  :: Member Report r => HSE.Binds HSE.SrcSpanInfo -> Sem r (S.Binds HSE)
+transformBinds (HSE.BDecls s decls) = do
```
Comment (stu204146-kiel) [inline src/lib/HST/Frontend/FromHSE.hs]: Here is a superfluous ``do``

**Review by stu204767 — APPROVED** [review]

**Review by stu204146-kiel — APPROVED** [review]
