### PR TITLE
Display Input Code Excerpts in Error Messages

### LINKED ISSUE #36: Improve error messages
## Description
If an error occurs during the pattern matching compilation because an unexpected construct is encountered in the AST, this construct should be shown to the user, preferably as pretty-printed code or as an extract of the original input program.

## Motivation
Seeing the place where something went wrong is always very helpful for programmers, especially if they don't know exactly how a correct program would look like, which might be the case for users of our pattern matching compiler because of the language constructs that are and aren't supported.

## Tasks
There are two points where error messages could be added or improved:
- For constructs that are not supported in general and are therefore not included in our own AST data structure, the error messages should be printed out during the transformation, i. e. in the `FromHSE` and the upcoming `FromGHC` module. During this state, we know which parser we have to use and also have access to the unsupported part of the untransformed AST, which means that we can easily use a pretty-printing function and also display the source span (currently, only generic error messages are printed out). If we wanted to display the extract of the input program, we could use functions like [`exactPrint`](https://hackage.haskell.org/package/haskell-src-exts-1.23.1/docs/Language-Haskell-Exts-ExactPrint.html#v:exactPrint) from `haskell-src-exts` (there is probably an equivalent function in `ghc-lib`, but if there isn't, we could pass down the source code of the original program to these transformation functions and use the source span information to extract the requested part).
- For errors that occur deeper within the algorithm, for example because a specific language construct is generally supported, but not in every location, printing these error messages becomes more difficult, because we don't know which parser we have to use. We can instead work with `Show` or other (custom) instances to display the AST. Using `show` to display the AST of the failing construct would be the easiest to implement and would also give the user all information available, but the error messages would be harder to read than direct source code. Another option would be to implement some kind of pretty instance for our syntax, which would probably involve using the transformation functions in `ToHSE` and `ToGHC` and then the respective pretty-printing functions.
Some of the places where these error messages could be useful are the lines that were commented out with the switch to the new syntax in #30 (`show` and especially `prettyPrint` can't be used anymore without at least requiring the corresponding instance). 

For both of these kinds of error messages, the new error handling methods of #28 should be used.

### PR DESCRIPTION
**Pull request by stu204767**
### Issue
Closes #36.

### Description of the Change
* An Effect allowing access to the file path and content of an input file is added.
* Types and type classes allowing access of the line and column data for both `haskell-src-exts` and `ghc-lib-parser` source spans are added.
* Functions using source span and input file data to display excerpts of the input code in an user-friendly way are added.
* The transformation functions in the `HST.Frontend.HSE.From` and `HST.Frontend.GHC.From` modules are adjusted to display these input excerpts for unsupported language constructs.
* Input excerpts are also displayed for many other errors occuring during the pattern matching compilation. (This point may be covered by a different pull request.)
* The input code excerpts are displayed in the following way:
* Single-line excerpts:
```
Error: Enumerations are not supported!
head.hs:8:8-8:16:
8 | test = [1 .. 5] ++ [6]
           ^^^^^^^^
```
* Multi-line excerpts:
```
Error: Enumerations are not supported!
head.hs:8:8-10:16:
            vvvvvvvv
 8 | test = [1
 9 |           ..
10 |              5] ++ [6]
            ^^^^^^^^
```
```
Error: Enumerations are not supported!
head.hs:8:8-11:11:
            vvvvv
 8 | test = [1
 9 |           ..
10 |    5
11 |          ] ++ [6]
        ^^^^^^^
```

### Alternate Designs
Some alternate designs are mentioned in #36. These designs have been discussed in the meeting on Friday, in which the proposed design has been agreed on.

### Verification Process
I tested the code excerpts with some not supported constructs (the examples above and some more), different file paths and with both front ends.

### Additional Notes
* In order to not clutter the output, code excerpts are currently only shown for fatal errors, i. e. not for `skipNotSupported`. I think we should implement some kind of option for enabling or disabling messages for these skipped parts.
* Initially, I wanted colorize the spanned source code, but since not all terminals support ANSI escape code sequences directly and I didn't want to use an IO monad for that (see [here](https://hackage.haskell.org/package/ansi-terminal)), I ultimately chose against colorized code.
* Unlike single-line excerpts, which should be fairly easy to understand (I chose a representation very similar to regular Haskell error messages), multi-line excerpts are a bit more comlicated. To be as compact as possible while still marking the exact start and end of the spanned code, I chose to add a line above and below the excerpt:
  * In the upper line, the symbols (`v`) start with the beginning of the spanned code and end with the end of the longest line contained in the code excerpt, where the last line counts until the end of the spanned code.
  * In the lower line, the symbols (`^`) start with the first non-space symbol of any line contained in the code excerpt, where the first line counts from the beginning of the spanned code, and end with the end of the spanned code.

### CODE REVIEW

File: src/lib/HST/Frontend/Syntax.hs [hunk 1]
```diff
@@ -438,3 +441,29 @@ instance Eq (SrcSpan a) where
...
+--   This type is not used for storing source span information, but to provide
+--   an interface for displaying source code excerpts which instantiations of
+--   the 'SrcSpanType' type family can be transformed into.
+data SimpleSrcSpan = SimpleSrcSpan
+  { startLine   :: Int
+  , startColumn :: Int
+  , endLine     :: Int
+  , endColumn   :: Int
+  }
+ deriving ( Eq, Show )
```
Comment (just95) [inline src/lib/HST/Frontend/Syntax.hs]: Why don't we just make this part of the `SrcSpan` data type, i.e., something like the following?

```haskell
data SrcSpan a
  = SrcSpan { srcSpanStartLine   :: Int
            , srcSpanStartColumn :: Int
            , srcSpanEndLine     :: Int
            , srcSpanEndColumn   :: Int
            , originalSrcSpan    :: SrcSpanType a
            }
  | NoSrcSpan
```

This would make the code much simpler since no type classes and wrapper data types are required for the conversion.

Does the source span of GHC-lib contain the file name? If it does, it should be part of the source span. Once we add support for the module system (see #11) we cannot be sure that the source span belongs to the current input file.

By convention, the names of the fields should contain `srcSpan`.

File: src/lib/HST/Effect/InputFile.hs [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+{-# LANGUAGE TemplateHaskell #-}
+
+-- | This module defines an effect for computations that can store the file
+--   path and the content of an input file.
+module HST.Effect.InputFile
+  ( -- * Effect
+    InputFile
+    -- * Actions
+  , setFile
+  , getFile
```
Comment (just95) [inline src/lib/HST/Effect/InputFile.hs]: I think that the names should be as follows.

```suggestion
  , setInputFile
  , getInputFile
```

File: src/lib/HST/Effect/InputFile.hs [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+--   to set new file data.
+runWithInputFile :: (FilePath, [String]) -> Sem (InputFile ': r) a -> Sem r a
+runWithInputFile initialFileData = evalState initialFileData . inputFileToState
+ where
+  -- | Reinterprets 'InputFile' in terms of 'State'.
+  inputFileToState
+    :: Sem (InputFile ': r) a -> Sem (State (FilePath, [String]) ': r) a
+  inputFileToState = reinterpret \case
+    SetFile path content -> put (path, lines content)
+    GetFile              -> get
```
Comment (just95) [inline src/lib/HST/Effect/InputFile.hs]: Make sure to [end every file with a new line](https://github.com/FreeProving/guidelines/blob/main/CONTRIBUTING.md#include-newline-at-end-of-file). Same in `src/lib/HST/Frontend/HSE/Config.hs` and `src/lib/HST/Frontend/Syntax.hs`.

File: src/lib/HST/Effect/InputFile.hs [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+-------------------------------------------------------------------------------
+-- Effect and Actions                                                        --
+-------------------------------------------------------------------------------
+-- | An effect capable of setting and getting the file path and the content of
+--   the input file.
+--
+--   While setting the input file, the content is converted to lines of code.
+data InputFile m a where
+  SetFile :: FilePath -> String -> InputFile m ()
+  GetFile :: InputFile m (FilePath, [String])
```
Comment (just95) [inline src/lib/HST/Effect/InputFile.hs]: If the file name is added to the source span, it would make sense to generalize this effect such that there can be multiple input files.

```suggestion
  GetFile :: FilePath -> InputFile m [String]
```

This would mean that a map has to be stored by `runWithInputFile` but would provide a cleaner default value for `runInputFile`.

Comment (just95) [inline src/lib/HST/Effect/InputFile.hs]: I'm not sure whether a reader effect may not be more appropriate in this situation, i.e., remove the `SetFile` action. This would also be more flexible since we could add an alternative handler that reads the file using `IO` (plus caching).

**Review by just95 — CHANGES_REQUESTED** [review]

File: src/exe/Main.hs [hunk 5]
```diff
@@ -99,11 +101,13 @@ application = do
...
 --   its parent directories are created.
-processInputFile
-  :: Members '[Cancel, Embed IO, GetOpt, Report] r => FilePath -> Sem r ()
+processInputFile :: Members '[Cancel, Embed IO, GetOpt, InputFile, Report] r
+                 => FilePath
+                 -> Sem r ()
 processInputFile inputFilename = do
   input <- embed $ readFile inputFilename
   frontend <- parseFrontend =<< getOpt optFrontend
+  _ <- addInputFile inputFilename input
```
Comment (stu204146-kiel) [inline src/exe/Main.hs]: Why did you add a wildcard?

File: src/lib/HST/Frontend/Transformer/Messages.hs [hunk 6]
```diff
@@ -24,3 +26,142 @@ skipNotSupported
...
+--   numbers, and marks showing the start and end of the spanned code.
+displayCodeExcerpt :: Member InputFile r => S.SrcSpan a -> Sem r String
+displayCodeExcerpt S.NoSrcSpan = return "No source span information available!"
+displayCodeExcerpt src@S.SrcSpan {} = do
+  maybeContent <- getInputFile (S.srcSpanFilePath src)
+  return $ case maybeContent of
+    Nothing      ->
+      "No content was found for the file `" ++ S.srcSpanFilePath src ++ "`!"
+    Just content ->
+      let ls = getLines (S.srcSpanStartLine src - 1) (S.srcSpanEndLine src)
```
Comment (stu204146-kiel) [inline src/lib/HST/Frontend/Transformer/Messages.hs]: I think it would be better to put the `-1` into the function `getLines` because the `-1` after `S.srcSpanStartLine src` can be confusing.

File: src/lib/HST/Frontend/Transformer/Messages.hs [hunk 7]
```diff
@@ -24,3 +26,142 @@ skipNotSupported
...
+           else S.srcSpanFilePath src
+             ++ ':' : srcString ++ ":\n" ++ unlines (prettyLines ls)
+ where
+  -- | Returns a sublist of the given list specified by the given indices.
+  --
+  --   The first of the zero-based indices is inclusive, the second is
+  --   exclusive. Invalid indices do not cause runtime errors.
+  --   Example: getLines 1 3 [1, 2, 3, 4, 5] = [2, 3]
+  getLines :: Int -> Int -> [a] -> [a]
+  getLines i1 i2 ls = (take (i2 - i1) . drop i1) ls
```
Comment (stu204146-kiel) [inline src/lib/HST/Frontend/Transformer/Messages.hs]: Here should be an eta-reduction.
```suggestion
  getLines i1 i2  = take (i2 - i1) . drop i1
```

File: src/lib/HST/Frontend/Transformer/Messages.hs [hunk 8]
```diff
@@ -24,3 +26,142 @@ skipNotSupported
 skipNotSupported feature = report
   $ Message Info
   $ feature ++ " are not supported and will be skipped!"
+
+-- | Reports a fatal error that the given feature is not supported. Displays an
+--   excerpt of the input code specified by the given source span.
+notSupportedWithExcerpt
```
Comment (stu204146-kiel) [inline src/lib/HST/Frontend/Transformer/Messages.hs]: Are the old functions still used?

**Review by stu204146-kiel — CHANGES_REQUESTED** [review]

File: src/exe/Main.hs (hunk 5 above)
Comment (stu204767) [reply src/exe/Main.hs]: Because I remembered a GHC warning I once got for not explicitly assigning such a return value to wildcard. But the GHC probably won't complain in this case, so I will change that.

File: src/lib/HST/Frontend/Transformer/Messages.hs (hunk 8 above)
Comment (stu204767) [reply src/lib/HST/Frontend/Transformer/Messages.hs]: You mean `notSupported` and `skipNotSupported`? Yes, both are used. `notSupported` is used for very few locations where we don't have a source span or where we would display the entire module. `skipNotSupported` hasn't yet been replaced by `skipNotSupportedWithExcerpt` at all, actually. Look at the pull request description for more details and give me your opinion if you want.

File: src/lib/HST/Frontend/Transformer/Messages.hs (hunk 6 above)
Comment (stu204767) [reply src/lib/HST/Frontend/Transformer/Messages.hs]: I wanted `getLines` to be a generic sublist function, so I like it better the way it is now. And I don't think it is that confusing, there are `1`s added to or subtracted from these source span values at many places in this function and its subfunctions.

File: src/exe/Main.hs [hunk 9]
```diff
@@ -99,11 +101,13 @@ application = do
...
 --   its parent directories are created.
-processInputFile
-  :: Members '[Cancel, Embed IO, GetOpt, Report] r => FilePath -> Sem r ()
+processInputFile :: Members '[Cancel, Embed IO, GetOpt, InputFile, Report] r
+                 => FilePath
+                 -> Sem r ()
 processInputFile inputFilename = do
   input <- embed $ readFile inputFilename
   frontend <- parseFrontend =<< getOpt optFrontend
+  addInputFile inputFilename input
```
Comment (just95) [inline src/exe/Main.hs]: The idea of removing the `setInputFile`/`addInputFile` effect entirely that I've brought up in <https://github.com/FreeProving/haskell-src-transformations/pull/45#discussion_r475528988> would allow us to move `embed . readFile` into the `runInputFile` handler.

```suggestion
  input <- getInputFile inputFilename
  frontend <- parseFrontend =<< getOpt optFrontend
```

The benifit of this approach is that we could write tests for `processInputFile` that don't actually perform any IO by simply providing an alternative handler of the `InputFile` effect.

File: src/lib/HST/Effect/InputFile.hs [hunk 10]
```diff
@@ -0,0 +1,53 @@
...
+--   to add new input files.
+runWithInputFile :: Map FilePath [String] -> Sem (InputFile ': r) a -> Sem r a
+runWithInputFile initialFileMap = evalState initialFileMap . inputFileToState
+ where
+  -- | Reinterprets 'InputFile' in terms of 'State'.
+  inputFileToState
+    :: Sem (InputFile ': r) a -> Sem (State (Map FilePath [String]) ': r) a
+  inputFileToState = reinterpret \case
+    AddInputFile path content -> get >>= put . Map.insert path (lines content)
+    GetInputFile path         -> Map.lookup path <$> get
```
Comment (just95) [inline src/lib/HST/Effect/InputFile.hs]: There are also [`modify`](https://hackage.haskell.org/package/polysemy-1.3.0.0/docs/Polysemy-State.html#v:modify) and [`gets`](https://hackage.haskell.org/package/polysemy-1.3.0.0/docs/Polysemy-State.html#v:gets) functions for Polysemy's `State` effect.

```suggestion
    AddInputFile path content -> modify $ Map.insert path (lines content)
    GetInputFile path         -> gets $ Map.lookup path
```

File: src/test/HST/ApplicationTests.hs [hunk 11]
```diff
@@ -27,23 +28,23 @@ import qualified HST.Frontend.Syntax       as S
...
-  :: (forall f.
-      S.EqAST f
-      => Sem '[WithFrontend f, GetOpt, Cancel, Report, SetExpectation, Embed IO]
-      ())
-  -> IO ()
+runTest :: (forall f.
+            S.EqAST f
+            => Sem '[WithFrontend f, GetOpt, InputFile, Cancel, Report,
+  SetExpectation, Embed IO] ())
+        -> IO ()
```
Comment (just95) [inline src/test/HST/ApplicationTests.hs]: This formatting does not look right. I'll add this to the list of bugs that we have to report to the Floskell developers.

File: src/lib/HST/Frontend/Transformer/Messages.hs [hunk 12]
```diff
@@ -24,3 +26,142 @@ skipNotSupported
...
+  :: Members '[InputFile, Report] r
+  => String      -- ^ The name of the feature (plural) that is not supported.
+  -> S.SrcSpan a -- ^ The source span of the excerpt to display.
+  -> Sem r b
+notSupportedWithExcerpt feature srcSpan = do
+  excerpt <- displayCodeExcerpt srcSpan
+  reportFatal $ Message Error $ feature ++ " are not supported!\n" ++ excerpt
```
Comment (just95) [inline src/lib/HST/Frontend/Transformer/Messages.hs]: I think that the producer of the error message should not be responsible for formatting the excerpt. Instead the handler of the `Report` effect should be responsible for this.

```suggestion
  reportFatal $ Message srcSpan Error $ feature ++ " are not supported!"
```

This approach has multiple benefits.

 1. The message text can be compared to messages that are expected by a unit test more easily.
 2. The `Member InputFile r` constraint does not have to be passed through the program explicitly.
 3. The `notSupportedWithExcerpt` and `notSupported` functions can be unified (resolves <https://github.com/FreeProving/haskell-src-transformations/pull/45#discussion_r477294818>). If there is no code excerpt, no `S.NoSrcSpan` can be provided instead.
 4. Whenever a message is reported, we are forced (on type level) to consider whether there is a good except to show to the user.

File: src/lib/HST/Frontend/Transformer/Messages.hs [hunk 13]
```diff
@@ -24,3 +26,142 @@ skipNotSupported
...
+  insertColor' :: Int -> [String] -> Maybe [String]
+  insertColor' c (h:ls') = 
+  insertColor' _ [] = Nothing
+
+  insertAt :: Int -> a -> [a] -> Maybe [a]
+  insertAt 0 e list = Just (e : list)
+  insertAt i e [] = Nothing
+  insertAt i e (h:list') | i < 0 = Nothing
+                         | otherwise = fmap (h :) (insertAt (i - 1) e list')
+  -}
```
Comment (just95) [inline src/lib/HST/Frontend/Transformer/Messages.hs]: Colorization of error messages is a good idea. However, we should probably use a dedicated library for the insertion of ANSI escape codes. Let's tackle this in a separate issue.

File: src/lib/HST/Frontend/Transformer/Messages.hs [hunk 14]
```diff
@@ -24,3 +26,142 @@ skipNotSupported
...
+--   source span numbers, all lines of the input program that are at least
+--   partially contained in the given source span, including their line
+--   numbers, and marks showing the start and end of the spanned code.
+displayCodeExcerpt :: Member InputFile r => S.SrcSpan a -> Sem r String
+displayCodeExcerpt S.NoSrcSpan = return "No source span information available!"
+displayCodeExcerpt src@S.SrcSpan {} = do
+  maybeContent <- getInputFile (S.srcSpanFilePath src)
+  return $ case maybeContent of
+    Nothing      ->
+      "No content was found for the file `" ++ S.srcSpanFilePath src ++ "`!"
```
Comment (just95) [inline src/lib/HST/Frontend/Transformer/Messages.hs]: Since there is nothing the user can do about this, we can just ignore this silently and print no excerpt in this case and when the source span is invalid.

File: src/lib/HST/Frontend/Transformer/Messages.hs [hunk 15]
```diff
@@ -24,3 +26,142 @@ skipNotSupported
...
+           else S.srcSpanFilePath src
+             ++ ':' : srcString ++ ":\n" ++ unlines (prettyLines ls)
+ where
+  -- | Returns a sublist of the given list specified by the given indices.
+  --
+  --   The first of the zero-based indices is inclusive, the second is
+  --   exclusive. Invalid indices do not cause runtime errors.
+  --   Example: getLines 1 3 [1, 2, 3, 4, 5] = [2, 3]
+  getLines :: Int -> Int -> [a] -> [a]
+  getLines i1 i2 = take (i2 - i1) . drop i1
```
Comment (just95) [inline src/lib/HST/Frontend/Transformer/Messages.hs]: Shouldn't this be equivalent to the following?

```suggestion
  getLines i1 i2 = drop i1 . take i2
```

File: src/lib/HST/Frontend/Transformer/Messages.hs [hunk 16]
```diff
@@ -24,3 +26,142 @@ skipNotSupported
...
+  srcString :: String
+  srcString = show (S.srcSpanStartLine src)
+    ++ ':'
+    : show (S.srcSpanStartColumn src)
+    ++ '-' : show (S.srcSpanEndLine src) ++ ':' : show (S.srcSpanEndColumn src)
+
+  -- | Adds line numbers to each given line and adds marks showing the start
+  --   and end of the spanned code.
+  prettyLines :: [String] -> [String]
+  prettyLines ls
```
Comment (just95) [inline src/lib/HST/Frontend/Transformer/Messages.hs]: I'm not sure how helpful it is to show all lines of multi-line source spans. The GHC deals with multi-line source spans by showing only the first line. The `^^^` markers are followed by an ellipsis in this case to indicate that the source span has been truncated. 

```
Error: Enumerations are not supported!
head.hs:8:8-10:16:
   |
 8 | test = [1
   |        ^^...
```

Of course this is not perfect as the relevant information may be hiding in the truncated lines. However, when all lines are shown, the actual error message gets obfuscated. Since the text of the error message is more important than the code excerpt (which the user can simply lookup in their editor), I'd recommend to adopt the GHC's approach.

**Review by just95 — CHANGES_REQUESTED** [review]

File: src/lib/HST/Frontend/Transformer/Messages.hs (hunk 15 above)
Comment (stu204767) [reply src/lib/HST/Frontend/Transformer/Messages.hs]: Yes, but according to [this](https://stackoverflow.com/questions/8529814/get-a-sublist-in-haskell), the current order may be a bit more efficient.

File: src/lib/HST/Frontend/Transformer/Messages.hs (hunk 16 above)
Comment (stu204767) [reply src/lib/HST/Frontend/Transformer/Messages.hs]: This is not a big problem currently, because these excerpts are currently only shown for fatal errors, so we have a maximum of one excerpt per program call. I've written something about this in the pull request description, so please read it.
And while the GHC does display only one regular line of the input code, it practically displays much more in many cases describing the location of the error (I have constructed an example where it prints out as much as I want). I definitely think that we should display more than one line, but we could set a maximum in some way. One idea I have is to display up to five lines and to display the first two and last two lines of longer excerpts, like this:
```
head.hs:8:8-101:11:
             vvvvv
  8 | test = [1
  9 |           ..
  ⁝
100 |    5
101 |          ] ++ [6]
         ^^^^^^^
```

File: src/lib/HST/Frontend/Transformer/Messages.hs (hunk 13 above)
Comment (stu204767) [reply src/lib/HST/Frontend/Transformer/Messages.hs]: I've written something about this in the pull request description and I've also linked such a library, which I have looked a bit further into. If we want to support older Windows Terminals (older than the Windows 10 version of November 2015), we would need to use an IO monad everywhere where we want to print out code excerpts.

File: src/lib/HST/Frontend/Transformer/Messages.hs (hunk 16 above)
Comment (just95) [reply src/lib/HST/Frontend/Transformer/Messages.hs]: > This is not a big problem currently, because these excerpts are currently only shown for fatal errors

If multi-line code excerpts prevent us from having code excerpts in non-fatal messages, we do have a big problem :D Especially in case of non-fatal messages the user needs enough information to quickly decide whether they want to investigate the warning but not too much information that they miss the warning altogether.

> the GHC [...] practically displays much more in many cases describing the location of the error

While I am aware that the GHC often prints additional code (using it's pretty printer) in messages like "In a stmt of a 'do' block: …", the actual code excerpts (i.e., ["caret diagnostics"](https://hackage.haskell.org/package/ghc-8.10.1/docs/src/ErrUtils.html#getCaretDiagnostic)) include the first line only as far as I know.

> One idea I have is to display up to five lines and to display the first two and last two lines of longer excerpts

That would be a viable option. Alternatively, we could show the first line by default and add a command line flag to show multi-line excerpts.

File: src/lib/HST/Frontend/Transformer/Messages.hs (hunk 13 above)
Comment (just95) [reply src/lib/HST/Frontend/Transformer/Messages.hs]: What I actually wanted to say is that we should either create an issue if we want to look into this or delete the comment.

```suggestion
```

File: src/lib/HST/Frontend/Transformer/Messages.hs (hunk 16 above)
Comment (stu204767) [reply src/lib/HST/Frontend/Transformer/Messages.hs]: > If multi-line code excerpts prevent us from having code excerpts in non-fatal messages, we do have a big problem :D

Multi-line excerpts are not the reason I didn't implement code excerpts for `skipNotSupported` yet. I think we should offer an option to disable these warnings altogether.

File: src/lib/HST/Frontend/Transformer/Messages.hs (hunk 13 above)
Comment (stu204767) [reply src/lib/HST/Frontend/Transformer/Messages.hs]: Okay, I've deleted the comment for now, but we could still decide to use colorized text later.

File: src/exe/Main.hs (hunk 9 above)
Comment (stu204767) [reply src/exe/Main.hs]: I've implemented this in a63367d, but there are still some IO operations left in `processInputFile` (output to file or console).

File: src/lib/HST/Frontend/Transformer/Messages.hs (hunk 8 above)
Comment (stu204767) [reply src/lib/HST/Frontend/Transformer/Messages.hs]: The old functions have now been removed and the new functions have gotten their names.

File: src/lib/HST/Frontend/Transformer/Messages.hs (hunk 12 above)
Comment (stu204767) [reply src/lib/HST/Frontend/Transformer/Messages.hs]: This has now been implemented, but it required a lot more effort than expected. And I'm still unsure about a few things (see the `TODO` comments).

File: src/lib/HST/Effect/Report.hs [hunk 17]
```diff
@@ -54,13 +58,161 @@ import           HST.Effect.Cancel ( Cancel, cancel, runCancel )
...
+--   span start and end.
+prettyMsgSrcSpanNumbers :: S.MsgSrcSpan -> String
+prettyMsgSrcSpanNumbers src = show (S.msgSrcSpanStartLine src)
+  ++ ':'
+  : show (S.msgSrcSpanStartColumn src)
+  ++ '-'
+  : show (S.msgSrcSpanEndLine src) ++ ':' : show (S.msgSrcSpanEndColumn src)
+
+-- TODO Should the following function be in its own module? It can't be put
+-- back into 'HST.Frontend.Transformer.Messages' because of cyclic imports.
```
Comment (just95) [inline src/lib/HST/Effect/Report.hs]: We could move the entire code for messages into its own module.

File: src/exe/Main.hs [hunk 18]
```diff
@@ -88,7 +89,11 @@ application = do
       inputFiles <- getOpt optInputFiles
       if showHelp || null inputFiles
         then embed putUsageInfo
-        else runInputFile $ mapM_ processInputFile inputFiles
+        else 
+          -- TODO There probably is a better way to add actual input files to the
+          -- Report effect
+          runInputFile inputFiles . reportToHandleOrCancel stderr
+          $ mapM_ processInputFile inputFiles
```
Comment (just95) [inline src/exe/Main.hs]: Why does the handler need to know all input files in advance? Wouldn't it be possible to load the input files on demand by doing something like the following.

```haskell
maybeContents <- gets $ Map.lookup path
case maybeContents of
  Nothing -> do
    contents <- embed $ readFile path
    modify $ Map.insert path contents
    return contents
  Just contents -> return contents
```

I think this should allow us to invoke the `runInputFile` and `reportToHandleOrCancel` handlers just in `main`.

File: src/lib/HST/Effect/InputFile.hs [hunk 19]
```diff
@@ -0,0 +1,52 @@
...
+  GetInputFile :: FilePath -> InputFile m (Maybe String)
+
+makeSem ''InputFile
+
+-------------------------------------------------------------------------------
+-- Interpretations                                                           --
+-------------------------------------------------------------------------------
+-- | Handles a computation by reading the given files and providing a file map
+--   with their file paths and contents.
+runInputFile
```
Comment (stu204146-kiel) [inline src/lib/HST/Effect/InputFile.hs]: I think we should call the function `runInputFiles` because there can be multiple files in the given list.

File: src/lib/HST/Effect/Report.hs [hunk 20]
```diff
@@ -54,13 +58,161 @@ import           HST.Effect.Cancel ( Cancel, cancel, runCancel )
...
+-- | Displays an excerpt of the input code specified by the given source span.
+--
+--   The excerpt consists of an introductory line with the file path and the
+--   source span numbers, all lines of the input program that are at least
+--   partially contained in the given source span, including their line
+--   numbers, and marks showing the start and end of the spanned code.
+displayCodeExcerpt :: Member InputFile r => Maybe S.MsgSrcSpan -> Sem r String
```
Comment (stu204146-kiel) [inline src/lib/HST/Effect/Report.hs]: In my tests, I found out that `displayCodeExcerpt` can also display the following `SrcSpan` that is invalid.
`S.MsgSrcSpan "./example/ExampleQueue1.hs" 1 4 1 3`.

**Review by stu204146-kiel — CHANGES_REQUESTED** [review]

File: src/lib/HST/Frontend/Syntax.hs [hunk 21]
```diff
@@ -438,3 +442,27 @@ instance Eq (SrcSpan a) where
...
+--   source spans without type variables, which would cause problems in the
+--   "HST.Effect.Report" module.
+data MsgSrcSpan = MsgSrcSpan
+  { msgSrcSpanFilePath    :: FilePath
+  , msgSrcSpanStartLine   :: Int
+  , msgSrcSpanStartColumn :: Int
+  , msgSrcSpanEndLine     :: Int
+  , msgSrcSpanEndColumn   :: Int
+  }
+ deriving ( Eq, Show )
```
Comment (just95) [inline src/lib/HST/Frontend/Syntax.hs:488]: I think the only reason why the `MsgSrcSpan` data type cannot be in the same module as the remaining message code is that the `message` smart constructor takes a `S.SrcSpan`. By adding a type class for `toMsgSrcSpan`, this dependency could be eliminated.

**Review by just95 — CHANGES_REQUESTED** [review]

File: src/lib/HST/Effect/InputFile.hs (hunk 19 above)
Comment (stu204767) [reply src/lib/HST/Effect/InputFile.hs]: If we rename that function, we should also rename the effect and the module itself to `InputFiles`, in my opinion.
I can do that, if you want that, though I would personally leave the name as it is.

File: src/lib/HST/Effect/Report.hs (hunk 17 above)
Comment (stu204767) [reply src/lib/HST/Effect/Report.hs]: I think this new module should include the functions in `HST.Frontend.Transformer.Messages` and be located in the `Util` folder. What do you think?

File: src/exe/Main.hs (hunk 18 above)
Comment (stu204767) [reply src/exe/Main.hs]: That's the reason I didn't change the `InputFile` effect to use [Polysemy's `Reader` effect](https://hackage.haskell.org/package/polysemy-1.3.0.0/docs/Polysemy-Reader.html) initially, but used the `State` effect with an `addInputFile` method.
Can this somehow be implemented with the `Reader` effect (possibly with the unexplained `Local` action)? I thought (not) being able to change the state of the effect was the main difference between the `State` and `Reader` effect.
I can of course change `InputFile` to use the `State` effect once again.

File: src/lib/HST/Effect/Report.hs (hunk 17 above)
Comment (just95) [reply src/lib/HST/Effect/Report.hs]: The `Util` folder seems to be a good choice for the new module but I would recommend to keep the modules separate. Otherwise there is a cyclic dependency since the `HST.Frontend.Transformer.Messages` module uses the `Report` effect but `HST.Effect.Report` needs to import the new module.

File: src/exe/Main.hs (hunk 18 above)
Comment (just95) [reply src/exe/Main.hs]: You can use Polysemy's `State` effect internally instead of the `Reader` effect even if the `InputFile` effect itself appears like a reader effect to the user since no equivalent to the `put` operation is exposed.

File: src/lib/HST/Frontend/Syntax.hs (hunk 21 above)
Comment (stu204767) [reply src/lib/HST/Frontend/Syntax.hs:488]: I would leave the `MsgSrcSpan` in this location, because I like that the `Syntax` module currently has no imports and stores the entirety of our ASTs in types defined in the module itself, except for the types represented by the type families. And I also think that `MsgSrcSpan` fits into the `Syntax` module: It was only created because there were problems with having a type variable in the `SrcSpan` type and I don't think this solution to these problems should cause the module these source span data are stored in to be changed.
However, if you really want to have `MsgSrcSpan` in the new `Message` module, I will move it.

File: src/lib/HST/Effect/Report.hs (hunk 20 above)
Comment (stu204767) [reply src/lib/HST/Effect/Report.hs]: This should be fixed now, but you should run your tests again to be sure that it's actually fixed and that I haven't introduced another bug.

**Review by just95 — APPROVED** [review]

**Review by stu204146-kiel — APPROVED** [review]
