### PR TITLE
Change Behaviour of Constructor Comparison

### LINKED ISSUE #7: Generation of `case` expressions with redundant alternatives
### Description

The tool sometimes produces `case` expressions with multiple alternatives for the same constructor when list patterns are used.

### Steps to Reproduce

1. Consider the following two example modules.

    ```haskell
    module A where

    foo :: [a] -> Integer
    foo []       = 1
    foo [x]      = 2
    foo (x : xs) = 3
    ```

    ```haskell
    module B where

    bar :: [a] -> Integer
    bar []       = 1
    bar (x : []) = 2
    bar (x : xs) = 3
    ```
2. Transform the modules with the following commands.

    ```bash
    haskell-src-transformations -I A.hs
    haskell-src-transformations -I B.hs
    ```

#### Expected behavior

The pattern `[x]` is just syntactic sugar for `x : []`. Thus, both modules should produce the same output (modulo renaming). The following output is produced for the module `B`.

```haskell
module B where

bar :: [a] -> Integer
bar a0
  = case a0 of
        [] -> 1
        a1 : a2 -> case a2 of
                       [] -> 2
                       a7 : a8 -> 3
```

#### Actual behavior

The output for `B` is as expected. However, the output for `A` contains two alternatives for the list constructor `(:)`.

```haskell
module A where

foo :: [a] -> Integer
foo a0
  = case a0 of
        [] -> 1
        a1 : a2 -> case a2 of
                       [] -> 2
                       a5 : a6 -> undefined
        a7 : a8 -> 3
```

### Versions

 - Git commit: 733088ab16ef3327ca8038a7b8cddc1c2ae2a2b7
 - `ghc --version`: 8.6.5
 - `cabal --version`: 2.4.1.0
 - OS: Ubuntu 19.10

### Known workarounds

It's possible to work around the issue by avoiding list patterns like in module `B`.

### PR DESCRIPTION
**Pull request by Daniel-Teut**
Currently the patterns `[x]` and `(x : [])` are considered to have two distinct constructors. This can lead to some unintended behaviour, such that a single constructor is matched more than once(#7).
Therefore change the comparison of constructors, such that the prefix and infix list constructor and the list notation are the same if the list is not empty. Closes #7.

The same is done for the tupel constructor. Now `(x, y)` and `(,) x y` are considered the same.

### CODE REVIEW

File: src/lib/Algo.hs [hunk 1]
```diff
@@ -292,12 +292,25 @@ compareCons (PInfixApp _ _ qn1 _) (PInfixApp _ _ qn2 _) = qn1 == qn2
...
+compareCons p1                    (PParen _ p2)         = compareCons p1 p2
+compareCons (PWildCard _) (PWildCard _)                 = True
+
+-- Lists have the same constructor if both are empty or both are non-empty.
+compareCons (PList _ []) (PList _ [])                   = True
+compareCons (PList _ (_ : _)) (PList _ (_ : _))         = True
+compareCons (PList _ (_ : _)) (PApp _ (Special () (Cons ())) _) = True
+compareCons (PApp _ (Special () (Cons ())) _) (PList _ (_ : _)) = True
+compareCons (PList _ (_ : _)) (PInfixApp _ _ (Special () (Cons ())) _) = True
+compareCons (PInfixApp _ _ (Special () (Cons ())) _) (PList _ (_ : _)) = True
```
Comment (just95) [inline src/lib/Algo.hs]: Currently, you have to consider all combinations of `PList`, `PApp` and `PInfixApp`. I imagine that a function with the following type signature could be useful to simplify this definition.

```haskell
consName :: Pat () -> Maybe (QName ())
```

`compareCons` whould now be ``(==) `on` consName``. It would supprise me, if there wasn't a function like that already.

**Review by just95 — CHANGES_REQUESTED** [review]
Looks good to me. I've commented below with a possible simplification of `compareCons` in general.
This may be a good opportunity to [add very basic unit tests](https://github.com/FreeProving/haskell-src-transformations/issues/5). There is already a `Hspec` skeleton in `src/test`. You would have to add a `parseTestPat` function and some test cases to verify that the constructors of `[x]` and `x : xs` are considered equal. I'd recommend to add the test first, make sure that is passes and than perform regression testing by implementing the suggestion below.

File: src/test/AlgoTests.hs [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+import           Control.Monad                  ( void )
+import           Language.Haskell.Exts
+import           Test.Hspec
+import           Test.HUnit.Base                ( assertFailure )
+
+import           Algo
+
+-- | Tests for the "Algo" module.
+testAlgo :: Spec
+testAlgo = context "Algo" testCompareCons
```
Comment (just95) [inline src/test/AlgoTests.hs]: I would switch `context` and `describe` such that the tests are more consistent with the tests of the Free Compiler. But apart from this minor detail, the tests look good to me : )

File: src/lib/Algo.hs [hunk 3]
```diff
@@ -287,17 +290,20 @@ select (ps, _) (qs, _) = compareCons (head ps) (head qs)
...
+consName :: Pat () -> Maybe (QName ())
+consName (PApp _ qn _       ) = return qn
+consName (PInfixApp _ _ qn _) = return qn
+consName (PParen _ pat      ) = consName pat
+consName (PList  _ []       ) = return $ Special () $ ListCon ()
+consName (PList  _ (_ : _)  ) = return $ Special () $ Cons ()
+consName (PTuple _ _ ps) = return $ Special () $ TupleCon () Boxed $ length ps
+consName (PWildCard _       ) = Nothing
+consName pat =
+  error $ "consName: unsupported pattern \"" ++ prettyPrint pat ++ "\""
```
Comment (just95) [inline src/lib/Algo.hs]: @macmaccamcam do you think it would be possible to reuse this function in [`getQNamePat`](https://github.com/FreeProving/haskell-src-transformations/blob/33c2fe955539f7be6422f5fb6629234aaf8ec1c2/src/lib/Algo.hs#L205)?

**Review by just95 — CHANGES_REQUESTED** [review]

**Review by just95 — APPROVED** [review]

File: src/lib/Algo.hs (hunk 3 above)
Comment (maclement) [reply src/lib/Algo.hs]: I can't think of any reason why it shouldn't.

**Review by maclement — APPROVED** [review]
