### PR TITLE
Fix name conflicts between user-defined and generated identifiers

### LINKED ISSUE #15: Fresh variables collide with user defined variables
### Description

The pattern matching compiler generates fresh variables of the form `aN` where `N ∈ [0, 1, …]`. It is not checked whether such variables are not used already. Thus, the pattern matching compiler gets confused if such variables are used.

### Steps to Reproduce

1. Consider the following module.

    ```haskell
    module Test where

    fst :: (a, b) -> a
    fst (a0, a1) = a0
    ```

2. Run the pattern matching compiler on the module above wtih one of the following commands.

    ```bash
    haskell-src-transformations -I Test.hs
    cabal new-run exe:haskell-src-transformations -- -I Test.hs
    ```

#### Expected Behavior

The compiler should choose a fresh variable `x ∉ {a0, a1, fst}` and produce the following result.

```haskell
module Test where

fst :: (a, b) -> a
fst x
  = case x of
        (a0, a1) -> a0
```

Alternatively, it would also be possible to choose `x = a0` provided variables are renamed appropriately.

```haskell
module Test where

fst :: (a, b) -> a
fst a0
  = case a0 of
        (a1, a2) -> a1
```

#### Actual Behavior

The following output is produced.

```haskell
module Test where

fst :: (a, b) -> a
fst a0
  = case a0 of
        (a1, a2) -> a2
```

I think the following is happening.

```haskell
module Test where

fst :: (a, b) -> a
fst a0 
   -- `a0` is selected as a fresh variable for the first argument.
  = ⟦ match [a0] [([(a0, a1)], a0)] undefined ⟧
  -- Since there are just constructor patterns, Rule 2 can be applied.
  -- Fresh variables `a1` and `a2` are selected for the constructor pattern.
  = case a0 of { (a1, a2) -> ⟦ match [a1, a2] [([a0, a1], a0)] undefined ⟧ }
  -- Rule 1 can be applied since the first pattern `a0` is a variable pattern.
  -- All occurrences of `a0` are replaced by `a1`.
  = case a0 of { (a1, a2) -> ⟦ match [a2] [([a1], a1)] undefined ⟧ }
  -- Rule 1 can be applied since the first pattern `a1` is a variable pattern.
  -- All occurrences of `a1` are replaced by `a2`.
  = case a0 of { (a1, a2) -> ⟦ match [] [([], a2)] undefined ⟧ }
  -- Rule 3a can be applied since all patterns have been matched.
  = case a0 of { (a1, a2) -> a2 }
```

Because the fresh variables are not actually fresh, variables of the user get renamed.

### Versions

 - Git commit: 504cf38dbb871def1b625eccab4ec6070e8a9c2f 
 - `ghc --version`: 8.6.5 
 - `cabal --version`: 2.4.1.0 
 - OS: Ubuntu 19.10 

### Known Workarounds

Don't use variables of the form `aN`.

### PR DESCRIPTION
**Pull request by stu204146-kiel**
### Issue

Closes #15.

### Description of the Change
Now prefixes are chosen such that generated variables do not collide with user-defined variables.
All variables occuring in the given module are collected in a set. This set is given to the `Fresh` handler that now checks whether the given prefix with its current ID is already in the module. If the identifier occurs in the module, then the counter is incremented until it finds a variable that is not used.

### Possible Drawbacks
Collecting all identifiers in the module is very inefficient.

### Verification Process

I tested the program given in the issue.

### CODE REVIEW

File: src/lib/HST/Effect/Fresh.hs [hunk 1]
```diff
@@ -57,16 +59,23 @@ freshVarPat prefix = S.PVar S.NoSrcSpan <$> freshName prefix
...
     FreshIdent prefix -> do
       nextId <- gets $ Map.findWithDefault (0 :: Int) prefix
-      modify $ Map.insert prefix (nextId + 1)
-      return (prefix ++ show nextId)
+      let newId = while (\n -> (prefix ++ show n) `Set.member` usedIdentifiers)
+            (+ 1) nextId
+      modify $ Map.insert prefix (newId + 1)
+      return (prefix ++ show newId)
+
+   -- Applies a given function to a given value as long as the condition holds
```
Comment (stu204767) [inline src/lib/HST/Effect/Fresh.hs]: I think this comment is the reason why the Haddock documentation build currently fails.
```suggestion
  -- | Applies the given function repeatedly to the given value as long as the
  --   condition holds.
```

File: src/lib/HST/Effect/Fresh.hs [hunk 2]
```diff
@@ -57,16 +59,23 @@ freshVarPat prefix = S.PVar S.NoSrcSpan <$> freshName prefix
 -------------------------------------------------------------------------------
 -- | Interprets a computation that needs fresh variables by generating
 --   identifiers of the form @<prefix><N>@.
```
Comment (stu204767) [inline src/lib/HST/Effect/Fresh.hs]:
```suggestion
--   identifiers of the form @<prefix><N>@ that do not collide with the given
--   set of used identifiers.
```

File: src/lib/HST/Util/Selectors.hs [hunk 3]
```diff
@@ -89,3 +94,96 @@ getPatVarName (S.PTuple _ _ _) = reportFatal
 getPatVarName (S.PList _ _) = reportFatal
   $ Message Error
   $ "Expected variable or wildcard pattern, got list pattern."
+
+-------------------------------------------------------------------------------
+-- Find identifiers in a programs                                                             --
+-------------------------------------------------------------------------------
```
Comment (stu204767) [inline src/lib/HST/Util/Selectors.hs]:
```suggestion
-------------------------------------------------------------------------------
-- Find Identifiers in Modules                                               --
-------------------------------------------------------------------------------
```

File: src/lib/HST/Util/Selectors.hs [hunk 4]
```diff
@@ -89,3 +94,96 @@ getPatVarName (S.PTuple _ _ _) = reportFatal
...
+getIdentifiersExp (S.Case _ scrutinee alts)  = Set.union
+  (getIdentifiersExp scrutinee) (Set.unions (map getIdentifiersAlt alts))
+getIdentifiersExp (S.Tuple _ _ exps)         = Set.unions
+  (map getIdentifiersExp exps)
+getIdentifiersExp (S.List _ exps)            = Set.unions
+  (map getIdentifiersExp exps)
+getIdentifiersExp (S.Paren _ expr)           = getIdentifiersExp expr
+getIdentifiersExp (S.ExpTypeSig _ expr _)    = getIdentifiersExp expr
+
+-- | collects all identifiers in a `case` alternative.
```
Comment (stu204767) [inline src/lib/HST/Util/Selectors.hs]:
```suggestion
-- | Collects all identifiers in a @case@ alternative.
```

File: src/lib/HST/Util/Selectors.hs [hunk 5]
```diff
@@ -89,3 +94,96 @@ getPatVarName (S.PTuple _ _ _) = reportFatal
...
+getIdentifiersAlt :: S.Alt a -> Set String
+getIdentifiersAlt (S.Alt _ pat rhs binds) = Set.union (getIdentifiersPat pat)
+  (Set.union (getIdentifiersRhs rhs) (maybe Set.empty getIdentifiersBinds binds))
+
+-- | Collects all identifiers in `let` and `while` bindings.
```
Comment (stu204767) [inline src/lib/HST/Util/Selectors.hs]:
```suggestion
-- | Collects all identifiers in @let@ and @where@ bindings.
```

**Review by stu204767 — CHANGES_REQUESTED** [review]

File: src/lib/HST/Util/Selectors.hs [hunk 6]
```diff
@@ -89,3 +94,96 @@ getPatVarName (S.PTuple _ _ _) = reportFatal
...
+  (map getIdentifiersExp exps)
+getIdentifiersExp (S.Paren _ expr)           = getIdentifiersExp expr
+getIdentifiersExp (S.ExpTypeSig _ expr _)    = getIdentifiersExp expr
+
+-- | collects all identifiers in a `case` alternative.
+getIdentifiersAlt :: S.Alt a -> Set String
+getIdentifiersAlt (S.Alt _ pat rhs binds) = Set.union (getIdentifiersPat pat)
+  (Set.union (getIdentifiersRhs rhs) (maybe Set.empty getIdentifiersBinds binds))
+
+-- | Collects all identifiers in `let` and `where` bindings.
```
Comment (stu204767) [inline src/lib/HST/Util/Selectors.hs]:
```suggestion
-- | Collects all identifiers in @let@ and @where@ bindings.
```

File: src/lib/HST/Util/Selectors.hs [hunk 7]
```diff
@@ -89,3 +94,96 @@ getPatVarName (S.PTuple _ _ _) = reportFatal
 getPatVarName (S.PList _ _) = reportFatal
   $ Message Error
   $ "Expected variable or wildcard pattern, got list pattern."
+
+-------------------------------------------------------------------------------
+-- Find Identifiers in Modules                                               --
+-------------------------------------------------------------------------------
+-- | Collects all identifiers in a module in a set.
+getIdentifiers :: S.Module a -> Set String
```
Comment (just95) [inline src/lib/HST/Util/Selectors.hs]: Since there are variations of `getIdentifiers` for all kinds of nodes, we could move this into a type class. The type class would also allow patterns such as `maybe Set.empty` and `Set.unions .: map` to be abstracted away.

File: src/lib/HST/Util/Selectors.hs [hunk 8]
```diff
@@ -89,3 +94,96 @@ getPatVarName (S.PTuple _ _ _) = reportFatal
...
+  (map getIdentifiersExp exps)
+getIdentifiersExp (S.List _ exps)            = Set.unions
+  (map getIdentifiersExp exps)
+getIdentifiersExp (S.Paren _ expr)           = getIdentifiersExp expr
+getIdentifiersExp (S.ExpTypeSig _ expr _)    = getIdentifiersExp expr
+
+-- | Collects all identifiers in a @case@ alternative.
+getIdentifiersAlt :: S.Alt a -> Set String
+getIdentifiersAlt (S.Alt _ pat rhs binds) = Set.union (getIdentifiersPat pat)
+  (Set.union (getIdentifiersRhs rhs) (maybe Set.empty getIdentifiersBinds binds))
```
Comment (just95) [inline src/lib/HST/Util/Selectors.hs]: I'd try to write functions like `Set.union` and `Set.insert` in infix notation to improve readability (i.e., reduce the number of parentheses).

```suggestion
getIdentifiersAlt (S.Alt _ pat rhs binds) =
  getIdentifiersPat pat
    `Set.union` getIdentifiersRhs rhs
    `Set.union` maybe Set.empty getIdentifiersBinds binds
```

File: src/lib/HST/Util/Selectors.hs [hunk 9]
```diff
@@ -5,17 +5,22 @@ module HST.Util.Selectors
     expFromUnguardedRhs
     -- * Pattern Names
   , getAltConName
+  , getIdentifiers
```
Comment (just95) [inline src/lib/HST/Util/Selectors.hs]: Consider to rename this to `findIdentifiers` to communicate the linear complexity of the function.

File: src/lib/HST/Util/Selectors.hs [hunk 10]
```diff
@@ -89,3 +94,96 @@ getPatVarName (S.PTuple _ _ _) = reportFatal
...
+
+-- | Collects all identifiers in a guarded right-hand side.
+getIdentifiersGRhs :: S.GuardedRhs a -> Set String
+getIdentifiersGRhs (S.GuardedRhs _ cond expr) = Set.union
+  (getIdentifiersExp cond) (getIdentifiersExp expr)
+
+-- | Collects all identifiers in an expression.
+getIdentifiersExp :: S.Exp a -> Set String
+getIdentifiersExp (S.Var _ qname)            = Set.singleton (prettyName qname)
+getIdentifiersExp (S.Con _ qname)            = Set.singleton (prettyName qname)
```
Comment (just95) [inline src/lib/HST/Util/Selectors.hs]: You should either 
 - clarify in the documentation that not the identifiers but pretty-printed qualified names are returned,
 - return the `QName`s instead and let the caller decide what to do with them or
 - traverse the `QName`s and actually just return the identifiers.

The `Fresh` effect does not have to worry about special, symbolic or qualified names. Thus, I'd prefer the latter solution.

**Review by just95 — CHANGES_REQUESTED** [review]

File: src/lib/HST/Effect/Fresh.hs [hunk 11]
```diff
@@ -56,17 +58,26 @@ freshVarPat prefix = S.PVar S.NoSrcSpan <$> freshName prefix
...
+      let newId = while (\n -> (prefix ++ show n) `Set.member` usedIdentifiers)
+            (+ 1) nextId
+      modify $ Map.insert prefix (newId + 1)
+      return (prefix ++ show newId)
+
+  -- | Applies the given function repeatedly to the given value as long as the
+  --   condition holds.
+  while :: (a -> Bool) -> (a -> a) -> a -> a
+  while p f x | p x = while p f (f x)
+              | otherwise = x
```
Comment (just95) [inline src/lib/HST/Effect/Fresh.hs]: Instead of defining `while` you could use `until` and negate the predicate.

```suggestion
      let newId = until (\n -> (prefix ++ show n) `Set.notMember` usedIdentifiers)
            (+ 1) nextId
      modify $ Map.insert prefix (newId + 1)
      return (prefix ++ show newId)
```

File: src/lib/HST/Util/Selectors.hs [hunk 12]
```diff
@@ -89,3 +93,106 @@ getPatVarName (S.PTuple _ _ _) = reportFatal
...
+-------------------------------------------------------------------------------
+-- Class for all types that contain identifiers.
+class HasIdentifiers a where
+  findIdentifiers :: a -> Set String
+
+instance HasIdentifiers a => HasIdentifiers [a] where
+  findIdentifiers = Set.unions . map findIdentifiers
+
+instance HasIdentifiers a => HasIdentifiers (Maybe a) where
+  findIdentifiers = maybe Set.empty findIdentifiers
```
Comment (just95) [inline src/lib/HST/Util/Selectors.hs]: These two instances as well as the instances for `QName` and `Name`s don't have a Haddock comment.

File: src/lib/HST/Util/Selectors.hs [hunk 13]
```diff
@@ -89,3 +93,106 @@ getPatVarName (S.PTuple _ _ _) = reportFatal
...
+  findIdentifiers (S.Alt _ pat rhs binds) = findIdentifiers pat
+    `Set.union` findIdentifiers rhs
+    `Set.union` findIdentifiers binds
+
+-- | Collects all identifiers in @let@ and @where@ bindings.
+instance HasIdentifiers (S.Binds a) where
+  findIdentifiers (S.BDecls _ decls) = findIdentifiers decls
+
+instance HasIdentifiers (S.QName a) where
+  findIdentifiers (S.Qual _ _ name) = findIdentifiers name
```
Comment (just95) [inline src/lib/HST/Util/Selectors.hs:194]: I'm not too sure whether we should include identifiers if they are qualified. If an expression contains a name `M.a1` (but not the unqualified name `a1`), there is no name conflict with a fresh variable `a1`. However, it wouldn't hurt if we rename the fresh variable nontheless.

**Review by just95 — CHANGES_REQUESTED** [review]

File: src/lib/HST/Util/Selectors.hs (hunk 13 above)
Comment (stu204146-kiel) [reply src/lib/HST/Util/Selectors.hs:194]: I think we should choose different names to make it less confusing for the user.

**Review by just95 — APPROVED** [review]

File: src/lib/HST/Util/Selectors.hs [hunk 14]
```diff
@@ -96,94 +95,108 @@ getPatVarName (S.PList _ _) = reportFatal
...
 -------------------------------------------------------------------------------
+-- Class for all types that contain identifiers.
+class HasIdentifiers a where
+  findIdentifiers :: a -> Set String
+
+-- Collects all identifiers in a list of types containing identifiers
+instance HasIdentifiers a => HasIdentifiers [a] where
+  findIdentifiers = Set.unions . map findIdentifiers
+
+-- Collects all identifiers in a `Maybe` value if a value is present.
```
Comment (stu204767) [inline src/lib/HST/Util/Selectors.hs]: Note: The comment for the `Maybe` instance implied that the instance was not defined for `Nothing`.
```suggestion
-- | Class for all types that contain identifiers.
class HasIdentifiers a where
  findIdentifiers :: a -> Set String

-- | Collects all identifiers in a list of types containing identifiers.
instance HasIdentifiers a => HasIdentifiers [a] where
  findIdentifiers = Set.unions . map findIdentifiers

-- | Collects all identifiers in a `Maybe` value.
```

**Review by stu204767 — CHANGES_REQUESTED** [review]

**Review by stu204767 — APPROVED** [review]
