### PR TITLE
Remove bug for simple case expressions #50

### LINKED ISSUE #50: Simple `case` Expressions Cause Internal Errors
### Description
The pattern matching compiler suffers internal errors with simple functions containing `case` expressions. This obviously shouldn't be the case, especially since equivalent functions can be compiled without errors.

### Steps to Reproduce
1. Consider the follwing Haskell module:
```haskell
module Test where

foo x = case x of
          y -> x
```
2. Run the pattern matching compiler on the module above with one of the following commands:
```
haskell-src-transformations Test.hs
cabal new-run exe:haskell-src-transformations -- Test.hs
```

#### Expected Behavior
The transformed module should look like the input module, possibly with `y` renamed.

#### Actual Behavior
The following output is produced:
```
module Test where
Internal: src\lib\HST\Feature\CaseCompletion.hs:30:11-34: Non-exhaustive patterns in Case _ _ resAs
```
The cause of this problem are the following lines of the `completeCase` function in the `CaseCompletion` module mentioned in the error message:
```haskell
  res <- match [v] eqs' defaultErrorExp
  if not insideLet
    then do
      let (S.Case _ _ resAs) = res
      return $ S.Case S.NoSrcSpan expr resAs  -- test to deconstruct the first case
```

### Versions
 - Git commit: 0302f8b
 - `ghc --version`: 8.6.5
 - `cabal --version`: 3.2.0.0
 - OS: Windows 10 (Version 1909)

### Known Workarounds
The error does not occur in the following Haskell module equivalent to the problematic one:
```haskell
module Test where

foo x = let r = case x of
                  y -> x
        in  r
```
For this module, the following output module is produced:
```haskell
module Test where
foo x
  = let r = case x of
                a0 -> x
      in r
```

### PR DESCRIPTION
**Pull request by stu204146-kiel**
### Issue

Closes #50 

### Description of the Change
I have changed the case completion such that simple case expressions are matched correctly.

### Verification Process
I have tested it with the module given in the issue and the basic unit tests already given.

### CODE REVIEW

File: src/lib/HST/Feature/CaseCompletion.hs [hunk 1]
```diff
@@ -19,57 +19,62 @@ completeCase :: (Members '[Env a, Fresh, GetOpt, Report] r, S.EqAST a)
...
-      return $ S.Case S.NoSrcSpan expr [a]
-completeCase il (S.InfixApp _ e1 qop e2)  = do
+  if not insideLet then do
+    if isCase res
+      then do
+        let (S.Case _ _ resAs) = res
+        return $ S.Case S.NoSrcSpan expr resAs  -- test to deconstruct the first case
+      else return ce else do
+    let a = S.alt v res
+    return $ S.Case S.NoSrcSpan expr [a]
```
Comment (just95) [inline src/lib/HST/Feature/CaseCompletion.hs]: I'm not sure why Floskell formats the code like this, but we could use `MultiWayIf`s to make this more readable.

```suggestion
  if | insideLet -> return $ S.Case S.NoSrcSpan expr [S.alt v res]
     | isCase res -> let S.Case _ _ resAs = res
                     in return $ S.Case S.NoSrcSpan expr resAs
     | otherwise -> return ce
```

However, I'm not entirely sure whether this code is correct in general.

 - In no case the case completion algorithm is applied to the scrutinee. This is probably a bug and could be fixed by adding the following statement.

   ```haskell
   expr' <- completeCase insideLet expr
   ```

 - In the `otherwise` case, the original `case`-expression is returned. Shouldn't case completion be performed at least recusively? `res` cannot be returned directly because it may contain `v`. In order to bind `v`, a `case` expression would have to be inserted like in the `insideLet` case.

   ```haskell
   return $ S.Case S.NoSrcSpan expr [S.alt v res]
   ```

 - Why is it safe to discard the scrutinee if `res` is a `case`-expression?
   My guess is that the scutinee is (assumed to be) always `v` and thus, the alternatives of the `case` expression can be inlined.

 - Why do `let` expressions have to be handled differently? If the above is true, why can't this optimization be applied inside `let`-expressions? According to the [Haskell 2010 Language Report (p. 33, Figure 3.2j)](https://www.haskell.org/definition/haskell2010.pdf) the following identity holds.

   ```haskell
   case v of { x -> e } = (\x -> e) v
   ```

   Thus, we should be able to substitute `v` directly (if `v` occurs only once in `res`).

   ```haskell
   return $ applySubst (singleSubst v expr') res
   ```

   Which would cover the case that `res` is a `case`-expression automatically.

**Review by just95 — CHANGES_REQUESTED** [review]

**Review by stu204767 — CHANGES_REQUESTED** [review]
I can't add much to what @just95 said. I think you should apply the suggestions and ideas he has given and check if the unit tests still work. After that, you could add some more tests explicitely for these changes (for all the sensible suggestions, they should fail before applying the suggestions and succeed after).

File: src/test/HST/ApplicationTests.hs [hunk 2]
```diff
@@ -115,17 +110,17 @@ testProcessModule = context "processModule" $ do
...
+    --    is not commented out, after the corresponding issue has been fixed.
+    it "avoids capture of variables shadowed in case expressions"
+      $ runTest
+      $ let m        = [ "module A where"
+                       , "f (x, y) = case x of"
+                       , "             y -> (x, y)"
+                       ]
+            expected
+              = ["module A where", "f a1 = case a1 of (a2, a3) -> (a2, a2)"]
+        in m `shouldTransformTo` expected ---}
```
Comment (stu204767) [inline src/test/HST/ApplicationTests.hs]: All comments here and the entire following test case (that was the replacement test) should be removed.

**Review by stu204767 — CHANGES_REQUESTED** [review]

**Review by stu204767 — CHANGES_REQUESTED** [review]
You removed the wrong test. The test containing a `let` expression was the replacement that should be removed, not the one that was commented out (it was commented out because it caused the bug that has been fixed in this pull request).

**Review by stu204767 — APPROVED** [review]

**Review by just95 — APPROVED** [review]
